# Generated by Django 3.2.22 on 2023-11-21 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subscription Date')),
            ],
        ),
    ]
